# Generated by Django 4.1.5 on 2023-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='date_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
